name = "lab8-klienci-zamowienia"
main = "cf/worker.ts"
compatibility_date = "2026-01-05"

# Serwuj statyczne pliki UI z istniejÄ…cego katalogu
assets = { directory = "./app" }

[vars]
GEMINI_MODEL = "gemini-2.5-flash"
BACKEND_URL = "https://programowanie-aplikacji.onrender.com"
